# Generated by Django 5.1.1 on 2025-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_is_available_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
